### ISSUE TITLE
Add [CONFIG] tag

### ISSUE THREAD

**Issue by Tazer** [EzyWebwerkstaden/Docs#2]
We should add [CONFIG] tag and describe it on the git guidelines.

**Comment by Fredrik-Oberg** [comment]
I'm not sure I understand what value this would have?
The tags IMO is there to be described as a quick overview what _kind_ of change that was made, not what kind of file it changed.

This would make more sense if we had a more project based tag system. For instance [SERVICE], [HELPER], [CONTROLLER]....

I think it's enough to just say _"[FEATURE/FIX] Config update for mail error recipient."_

**Comment by johanwikstrom** [comment]
In my book FIX is a bug, FEATURE is new feature, CONFIG is just that, typically change a webconfig setting that is neither a bug or feature. I think we use FIX for everything and to much maybe..

**Comment by Fredrik-Oberg** [comment]
Yes valid point, but this tag will be for all the configuration changes and settings then?

**Comment by Fredrik-Oberg** [comment]
#5
