### ISSUE TITLE
Explain how a commit message should be like.

### ISSUE THREAD

**Issue by Tazer** [EzyWebwerkstaden/Docs#3]
We need to describe and show examples how we write the message. 
What the message should say and explain.

**Comment by markoezy** [comment]
issue number [TAG] a shorter description of what is done. A summary of the intent of the code. Describe WHY and WHAT in a clear language. If the description describes several items it's preferable to split those in several commits.

**Comment by Fredrik-Oberg** [comment]
Men det du då säger Marco, om jag förstår det rätt, är att vi ska göra så här.
```
Issue number [TAG] Description 

Summary ( Describe WHY and WHAT in a clear language.)
```

**Comment by markoezy** [comment]
issue number [TAG] Description 

Description = a shorter description of what is done. A summary of the intent of the code. Describe WHY and WHAT in a clear language. If the description describes several items it's preferable to split those in several commits. 

Klart nog? Förstår du?

**Comment by Fredrik-Oberg** [comment]
Problemet som jag ser med det är att ifall du vill ha allting på en rad så blir det så här.

![image](https://cloud.githubusercontent.com/assets/2648767/13316068/7bed6a88-dbae-11e5-9e16-1df46fe44415.png)

![image](https://cloud.githubusercontent.com/assets/2648767/13316056/6c851f14-dbae-11e5-8a29-62d07193141e.png)

Mitt förslag är hellre att i så stor utsträckning som möjligt ha en subject rad på max 75 tecken, (github bryter raden på 75 tecken).
Skrivas kort om vad eller varför. T.ex. om det är en bug så kan man skriva :
```
FA-999 [FIX] Taxes not applied on SSRs
Created a tax applier, that applies taxes when no taxes is applied (inte så relevant men ni förstår vad jag menar :) )
```
Exempel hur jag menar man kan skriva. :notebook: Hade inget Jira issue till den här fixen.
![image](https://cloud.githubusercontent.com/assets/2648767/13316486/96c2d7ec-dbb0-11e5-9017-af5b16845e09.png)


Här är en [slide](http://www.slideshare.net/TarinGamberini/commit-messages-goodpractices) om vaför det kan vara bra att skriva lite mer i ett commit meddelande.
Speciellt när vi håller på med att fixa till affärslogik som inte alltid är så "logisk".

Här finns mer resurser i ämnet.
* https://wiki.openstack.org/wiki/GitCommitMessages
* http://alistapart.com/article/the-art-of-the-commit

**Comment by Tazer** [comment]
Jag tycker de blir riktigt snyggt , när man har en rubrik och sen skriver lite mer utförligt vad man gjort som description. Som @Fredrik-Oberg  vissade :+1:

**Comment by Fredrik-Oberg** [comment]
Vidare så menar jag inte att det är __fel__ att ha mer än 75 tecken och det bryts. 
Men att man kan försöka tänka på det :smile:

**Comment by markoezy** [comment]
jättesnyggt! :+1:  Men kan rubriken vara jira titeln? ja bra riktmärke, ca 75 tecken.

**Comment by johanwikstrom** [comment]
Kan man få in syfte och vad man gjort på första raden (summary) utan att använda description så måste det vara ok va? Dvs om det inte kräver massa förklaring..

**Comment by Fredrik-Oberg** [comment]
Men om Jira titeln är [Upgrade NopCommerce to 3.7](https://jira.ezy.se/browse/NY-176).
Vad för värde har det i våran kod repo att det står:
```
NY-176 [FIX] Upgrade NopCommerce to 3.7

Removed old projects that did not build
```
Vi kan enkelt gå in och se i Jira att NY-176 har titlen "Upgrade NopCommerce to 3.7"

Så i mitt tycke så blir det bara noise som inte ger något värde till koden.
Som commiten är tycker jag funkar bra
```
NY-176 [FIX] Removed old projects that did not build
```

**Comment by Fredrik-Oberg** [comment]
Ja @johanwikstrom Det tycker jag. Men ifall man inte kan beskriva det på 75 tecken eller om det är så att det är någon ändring som man tycker inte är självklar i koden. _Varför gör vi X här??_ 
Så förtjänar det en kommentar och för att inte kommentera i koden så gör vi det i commiten istället.

**Comment by Tazer** [comment]
Fast där håller jag inte riktigt med , För om jag kollar igenom commitsen som är gjorde , Så är sånna grejer väldigt värdefulla. Dvs Removed old projects that did not build , säger mig inte så mkt. Men Upgrade NopCommerce to 3.7 förstår jag vad förslags kodändring det är. 

Men sen Upgrade NopCommerce to 3.7 kanske är ett dåligt exempel .. För de kan väl vart "vad man gjort också" 

Jag kan ju hålla med att typ "Payment Problems" som title inte ger något. (om vi har ett JIRA-X Payment Problems). Då vill man ju veta VAD man gjorde istället.

**Comment by Tazer** [comment]
Sen en FYI @markoezy @Fredrik-Oberg. Tänk på att repot är "öppet"  :)

Om vi känner att de är nödvändigt kan vi ju stänga de. Men då får vi kolla på någon annan lösning än readthedocs :)

**Comment by Fredrik-Oberg** [comment]
Om Jira titlen är bra så kan man ju ha den som subject. 
Det är ju samma sak som att skriva det själv för att förklara, fastän det råkar vara Jira titeln.

Men säg att du gör 5 commits på ett item, då känns det bara som noise att ha med jira titeln.
JIRA : FA-999 - Insurance problems 
```
FA-999 [FIX] Insurance problems
- vad och varför
FA-999 [FIX] Insurance problems
- vad och varför
FA-999 [FEATURE] Insurance problems
- vad och varför
FA-999 [FIX] Insurance problems
- vad och varför
FA-999 [TEST] Insurance problems
- vad och varför
```
Isåfall så kan man referera i "body" texten vilket item det är, men det känns lite overkill.
```
FA-999 [FIX] Taxes not applied on SSRs
- vad och varför
- JIRA : FA-999 - Insurance problems 
```

**Comment by ConnyH** [comment]
FA-999 [FIX] Added some logging
FA-999 [FEATURE] Made new validation for currency

Räcker det inte med jira itemidet?

**Comment by andreyezy** [comment]
Det står i [guidlines ](http://code.ezy.se/en/latest/guidlines/git/) att [TEST] ska användas för redigera tester, men hur ofta gör vi det? Aldrig?

```
PRJ-1 [TEST] when just editing tests
PRJ-1 [TEMP] when testing temporary changes
```

t.ex. [här](https://github.com/EzyWebwerkstaden/Safair/commit/78703c583accb0f9771d62e57264982d66f1f306) används det [TEST] som [TEMP] och det är logiskt om man vill testa något :)

**Comment by Tazer** [comment]
@andreyezy , kanske inte för de vanliga radixx projekten, men tex https://github.com/EzyWebwerkstaden/ezyFlight.Api/tree/master/src/test/ezyFlight.Api.Web.Tests 

har 60+ tester. och finns några andra projekt med mkt tester också :) Så tycker absolut den ska finnas kvar.

**Comment by Fredrik-Oberg** [comment]
Svävade ifrån subject lite här, bättre att skapa ett nytt issue nästa gång @andreyezy 
@ConnyH Jo jag tycker det räcker så, ser inga fördelar med att lägga in Jira titeln, ifall den inte är det man ändå tänkt skriva.

**Comment by Tazer** [comment]
Uppdaterade min draft lite, 

Vi kan väl försöka ge feedback på den. Så vi får ner något i skrift. Känns som vi ändå fått fram ganska bra vad vi vill?

**Comment by Tazer** [comment]
Tja!

Tänker att jag mergar in de jag gjorde, Så kan vi köra feedback på. Om vi tycker de ska ändras. 
Men då får man komma med konkreta förslag på text ändringar :)

Så jag stänger pull-request #4

**Comment by Tazer** [comment]
Stänger detta itemet , så får man gärna skapa upp en pullrequest för ändringar man skullle vilja få in :)
